name: Compiling QEMU IRIX on macOS 13

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    
    - name: Install required packages
      run: brew update && brew upgrade && brew install glib pixman

    - name: Configure
      run: ./configure --target-list=irix-darwin-user --disable-werror --disable-vnc --disable-sdl --disable-gtk --disable-cocoa --disable-opengl --disable-capstone --disable-hax --disable-hvf --disable-tools

    - name: Build
      run: gmake -j4

    - name: Install and check
      run: gmake install -j4
