name: Compiling QEMU IRIX All on macOS latest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install required packages
      run: brew update && brew upgrade && brew install glib pixman

    - name: Configure
      run: ./configure --target-list=irix-darwin-user,irixn32-darwin-user,irix64-darwin-user,solaris-darwin-user --disable-werror --disable-vnc --disable-sdl --disable-gtk --disable-cocoa --disable-opengl --disable-capstone --disable-hax --disable-hvf --disable-tools

    - name: Build
      run: make -j3

    - name: Install and check
      run: sudo make install -j3
