name: Compiling on Ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  compiling:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install required packages
      run: apt-get update && apt-get upgrade -y && apt-get install build-essential

    - name: Configure
      run: ./configure --target-list=irix-linux-user

    - name: Install dependencies
      run: make

    - name: Install qemu irix
      run: make install
