name: Compiling on Ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Compiling QEMU IRIX:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install required packages
      run: sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install libglib2.0-dev libpixman-1-dev

    - name: Configure
      run: ./configure --target-list=irix-linux-user --disable-werror

    - name: Build QEMU IRIX
      run: make -j$(nproc)

    - name: Install QEMU IRIX
      run: sudo make install -j$(nproc)

  Compiling QEMU IRIXN32:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install required packages
      run: sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install libglib2.0-dev libpixman-1-dev

    - name: Configure
      run: ./configure --target-list=irixn32-linux-user --disable-werror

    - name: Build QEMU IRIXN32
      run: make -j$(nproc)

    - name: Install QEMU IRIXN32
      run: sudo make install -j$(nproc)

  Compiling QEMU IRIX64:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install required packages
      run: sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install libglib2.0-dev libpixman-1-dev

    - name: Configure
      run: ./configure --target-list=irix64-linux-user --disable-werror

    - name: Build QEMU IRIX64
      run: make -j$(nproc)

    - name: Install QEMU IRIX64
      run: sudo make install -j$(nproc)

  Compiling QEMU Solaris:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install required packages
      run: sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install libglib2.0-dev libpixman-1-dev

    - name: Configure
      run: ./configure --target-list=solaris-linux-user --disable-werror

    - name: Build QEMU Solaris
      run: make -j$(nproc)

    - name: Install QEMU Solaris
      run: sudo make install -j$(nproc)
