name: QEMU IRIX build on Ubuntu latest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: ./configure --target-list=irix-linux-user

    - name: Install dependencies
      run: make
